{% set name = "tcsh" %}
{% set version = "6_22_03" %}

package:
  name: {{ name|lower }}
  version: {{ version | replace("_", ".") }}

source:
  url: https://github.com/tcsh-org/tcsh/archive/TCSH{{ version }}.tar.gz
  sha256: dd6f3ef7a88d4a1c34636b65d2dc0502ea2e620567e6af4eba93c463bcea4e64

build:
  number: 0
  skip: true  # [win]
  script:
    - ./configure --prefix={{ PREFIX }}
    - make
    - make install
    - make install.man


requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - ncurses
  run:
    - ncurses

test:
  commands:
    - tcsh --version

about:
  home: https://web.archive.org/web/20100212221424/http://www.tcsh.org/Home
  license: Public Domain
  license_file: Copyright
  summary: tcsh shell is an enhanced but completely compatible version of the Berkeley UNIX C shell
  description: |
    Tcsh is a version of the Berkeley C-Shell, with the addition of a 
    command line editor, command and file name completion, listing, etc.
    and a bunch of small additions to the shell itself.
  doc_url: https://web.archive.org/web/20100216160602/http://www.tcsh.org/tcsh.html/top.html
  dev_url: http://github.com/tcsh-org/tcsh

extra:
  recipe-maintainers:
    - bernt-matthias
