{% set name = "tcsh" %}
{% set version = "6_24_00" %}

package:
  name: {{ name|lower }}
  version: {{ version | replace("_", ".") }}

source:
  url: https://github.com/tcsh-org/tcsh/archive/TCSH{{ version }}.tar.gz
  sha256: a9ad7e2725b64d3ef953aac86096561e18827a9ce9b27f59d5f6e1e1b00829c9

build:
  number: 0
  skip: true  # [win]
  script:
    # tcsh does NOT recognize arm64 and expect arm
    # this sed call just edits the config.sub file to
    # replace all mentions of arm to arm64 and thus faking it to pass
    # however, this also leads to a version: unknown-apple-darwin in test
    # but, we don't test that... we should probably file an issue upstream...
    # issue upstream: https://github.com/tcsh-org/tcsh/issues/46
    - sed -i -e 's/arm/arm64/g' config.sub  # [osx and arm64]
    - ./configure --prefix={{ PREFIX }}
    - make
    - make install
    - make install.man


requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - ncurses
  run:
    - ncurses

test:
  commands:
    - tcsh --version

about:
  home: https://web.archive.org/web/20100212221424/http://www.tcsh.org/Home
  license: BSD-3-Clause
  license_file: Copyright
  summary: tcsh shell is an enhanced but completely compatible version of the Berkeley UNIX C shell
  description: |
    Tcsh is a version of the Berkeley C-Shell, with the addition of a 
    command line editor, command and file name completion, listing, etc.
    and a bunch of small additions to the shell itself.
  doc_url: https://web.archive.org/web/20100216160602/http://www.tcsh.org/tcsh.html/top.html
  dev_url: http://github.com/tcsh-org/tcsh

extra:
  recipe-maintainers:
    - bernt-matthias
